@node Режимы работы
@section Режимы работы

Есть три режима работы. Они предоставляют компромиссы между потреблением
ресурсов и эффективностью.

@table @asis

@item Режим по-умолчанию.

Пакеты с данными зашифрованы и аутентифицированы и посылаются сразу же.
Это наиболее эффективный режим с минимальными накладными расходами и
задержками.

@verbatim
         +-----------+   +-----+         +---------+    +------+
         |  DATA     |   |DATA |         |  DATA   |    | DATA |
         +-----------+   +-----+         +---------+    +------+

---------------------------------------------------------------------------------------> t
@end verbatim

@item @ref{Noise, Шумовой} режим.

Этот режим прячет длины пакетов. Как правило, он потребляет больше
трафика.

@verbatim
 +------const------+        +------const------+    +------const------+
/                   \      /                   \  /                   \

+------+------------+      +---------+---------+  +-------------+-----+
| DATA | NOISE      |      | DATA    | NOISE   |  | DATA        |NOISE|
+------+------------+      +---------+---------+  +-------------+-----+

---------------------------------------------------------------------------------------> t
@end verbatim

@item Режим постоянной @ref{CPR, скорости пакетов}.

Этот режим ещё и прячет временные характеристики пакетов. Он может
увеличить задержки и вставлять пустые шумовые пакеты.

@verbatim
 +------const------+             +------const------+             +------const------+
/                   \           /                   \           /                   \

+------+------------+           +---------+---------+           +-------------------+
| DATA | NOISE      |<--const-->| DATA    | NOISE   |<--const-->|       NOISE       |
+------+------------+           +---------+---------+           +-------------------+

---------------------------------------------------------------------------------------> t
@end verbatim

@end table
